#!/usr/bin/env python3
"""
Rasa Startup Script with Environment Variable Loading
Loads environment variables from .env file and starts Rasa server
"""

import os
import sys
import subprocess
from pathlib import Path
from dotenv import load_dotenv

def load_environment():
    """Load environment variables from .env file"""
    # Get the backend directory path
    backend_dir = Path(__file__).parent
    env_file = backend_dir / '.env'
    
    if env_file.exists():
        print(f"Loading environment variables from: {env_file}")
        load_dotenv(env_file)
        
        # Expand environment variables in RASA_ACTION_ENDPOINT_URL
        rasa_action_url = os.getenv('RASA_ACTION_ENDPOINT_URL', '')
        if rasa_action_url:
            # Replace ${DOMAIN} and ${RASA_ACTIONS_PORT} with actual values
            domain = os.getenv('DOMAIN', 'http://localhost')
            rasa_actions_port = os.getenv('RASA_ACTIONS_PORT', '5055')
            
            # Expand the variables
            expanded_url = rasa_action_url.replace('${DOMAIN}', domain)
            expanded_url = expanded_url.replace('${RASA_ACTIONS_PORT}', rasa_actions_port)
            
            # Set the expanded URL as environment variable
            os.environ['RASA_ACTION_ENDPOINT_URL'] = expanded_url
            print(f"Expanded RASA_ACTION_ENDPOINT_URL: {expanded_url}")
        
        print("Environment variables loaded successfully")
    else:
        print(f"Warning: .env file not found at {env_file}")
        print("Using default environment variables")

def generate_endpoints_yml():
    """Generate endpoints.yml with current environment configuration"""
    backend_dir = Path(__file__).parent
    endpoints_file = backend_dir / 'endpoints.yml'
    
    # Get the expanded action endpoint URL
    action_url = os.environ.get('RASA_ACTION_ENDPOINT_URL', 'http://localhost:5055/webhook')
    
    # Template for endpoints.yml
    endpoints_content = f"""# This file contains the different endpoints your bot can use.
# Auto-generated by start_rasa.py - DO NOT EDIT MANUALLY

# Server where the models are pulled from.
# https://rasa.com/docs/rasa/model-storage#fetching-models-from-a-server

#models:
#  url: http://my-server.com/models/default_core@latest
#  wait_time_between_pulls:  10   # [optional](default: 100)

# Server which runs your custom actions.
# https://rasa.com/docs/rasa/custom-actions

action_endpoint:
  url: "{action_url}"

# Tracker store which is used to store the conversations.
# By default the conversations are stored in memory.
# https://rasa.com/docs/rasa/tracker-stores

#tracker_store:
#    type: redis
#    url: <host of the redis instance, e.g. localhost>
#    port: <port of your redis instance, usually 6379>
#    db: <number of your database within redis, e.g. 0>
#    password: <password used for authentication>
#    use_ssl: <whether or not the communication is encrypted, default false>

#tracker_store:
#    type: mongod
#    url: <url to your mongo instance, e.g. mongodb://localhost:27017>
#    db: <name of the db within your mongo instance, e.g. rasa>
#    username: <username used for authentication>
#    password: <password used for authentication>

# Event broker which all conversation events should be streamed to.
# https://rasa.com/docs/rasa/event-brokers
# Note: Event logging is handled automatically by AutoLoggedAction base class
"""
    
    # Write the endpoints.yml file
    with open(endpoints_file, 'w', encoding='utf-8') as f:
        f.write(endpoints_content)
    
    print(f"Generated endpoints.yml with action_endpoint: {action_url}")

def start_rasa():
    """Start Rasa server with loaded environment variables"""
    try:
        # Change to backend directory
        backend_dir = Path(__file__).parent
        os.chdir(backend_dir)
        
        # Generate endpoints.yml with current environment
        generate_endpoints_yml()
        
        # Rasa command arguments
        rasa_cmd = [
            sys.executable, '-m', 'rasa', 'run',
            '--enable-api',
            '--cors', '*',
            '--port', '5005',
            '-i', '0.0.0.0',
            '--endpoints', 'endpoints.yml'
        ]
        
        print(f"Starting Rasa server with command: {' '.join(rasa_cmd)}")
        print(f"Working directory: {os.getcwd()}")
        
        # Start Rasa server
        subprocess.run(rasa_cmd, check=True)
        
    except subprocess.CalledProcessError as e:
        print(f"Error starting Rasa server: {e}")
        sys.exit(1)
    except KeyboardInterrupt:
        print("\nRasa server stopped by user")
        sys.exit(0)
    except Exception as e:
        print(f"Unexpected error: {e}")
        sys.exit(1)

if __name__ == '__main__':
    print("[RASA] Starting Rasa server with environment configuration...")
    load_environment()
    start_rasa()