#!/usr/bin/env python3
"""
Dynamic Deployment Configuration Script
This script allows easy switching between localhost and production (EC2) configurations
without hardcoding URLs in multiple files.
"""

import os
import sys
import json
import argparse
from pathlib import Path

# Configuration templates
CONFIG_TEMPLATES = {
    "localhost": {
        "domain": "http://localhost",
        "frontend_port": "3000",
        "backend_port": "8000",
        "rasa_port": "5005",
        "rasa_actions_port": "5055",
        "ssl_enabled": False
    },
    "ec2": {
        "domain": "http://54.254.180.103",
        "frontend_port": "3000",
        "backend_port": "8000",
        "rasa_port": "5005",
        "rasa_actions_port": "5055",
        "ssl_enabled": False
    },
    "production": {
        "domain": "https://your-domain.com",
        "frontend_port": "443",
        "backend_port": "443",
        "rasa_port": "5005",
        "rasa_actions_port": "5055",
        "ssl_enabled": True
    }
}

def get_project_root():
    """Get the project root directory"""
    script_path = Path(__file__).resolve()
    # Go up from scripts/ to project root
    return script_path.parent.parent

def update_backend_env(config, project_root):
    """Update backend/.env file with new configuration"""
    env_file = project_root / "backend" / ".env"
    
    # Read existing .env file
    env_content = {}
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_content[key] = value
    
    # Update domain-related configurations
    domain = config['domain']
    env_content['DOMAIN'] = domain
    env_content['FRONTEND_URL'] = f"{domain}:{config['frontend_port']}"
    env_content['BACKEND_URL'] = f"{domain}:{config['backend_port']}"
    env_content['RASA_URL'] = f"{domain}:{config['rasa_port']}"
    env_content['RASA_ACTIONS_URL'] = f"{domain}:{config['rasa_actions_port']}"
    
    # Update RASA action endpoint URL
    env_content['RASA_ACTION_ENDPOINT_URL'] = f"{domain}:{config['rasa_actions_port']}/webhook"
    
    # Write updated .env file
    with open(env_file, 'w') as f:
        f.write("# Environment Configuration\n")
        f.write(f"# Generated by configure-deployment.py\n")
        f.write(f"# Configuration: {get_config_name(config)}\n\n")
        
        for key, value in env_content.items():
            f.write(f"{key}={value}\n")
    
    print(f"✓ Updated {env_file}")

def update_rasa_endpoints(config, project_root):
    """Update RASA endpoints.yml file"""
    endpoints_file = project_root / "backend" / "endpoints.yml"
    
    domain = config['domain']
    action_endpoint = f"{domain}:{config['rasa_actions_port']}/webhook"
    
    endpoints_content = f"""# Rasa Endpoints Configuration
# Generated by configure-deployment.py
# Configuration: {get_config_name(config)}

action_endpoint:
  url: "{action_endpoint}"

# Uncomment and configure if using a tracker store
# tracker_store:
#   type: mongod
#   url: mongodb://localhost:27017
#   db: rasa
#   username: 
#   password: 
"""
    
    with open(endpoints_file, 'w') as f:
        f.write(endpoints_content)
    
    print(f"✓ Updated {endpoints_file}")

def update_docker_compose_env(config, project_root):
    """Update docker-compose environment file"""
    env_file = project_root / "aws-deployment" / "environments" / ".env.production"
    
    if not env_file.exists():
        print(f"Warning: {env_file} not found, skipping Docker environment update")
        return
    
    # Read existing file
    with open(env_file, 'r') as f:
        content = f.read()
    
    # Update domain-related variables
    domain = config['domain']
    
    # Replace domain configurations
    replacements = {
        'DOMAIN=': f'DOMAIN={domain}',
        'FRONTEND_URL=': f'FRONTEND_URL={domain}:{config["frontend_port"]}',
        'BACKEND_URL=': f'BACKEND_URL={domain}:{config["backend_port"]}',
        'RASA_URL=': f'RASA_URL={domain}:{config["rasa_port"]}',
        'RASA_ACTIONS_URL=': f'RASA_ACTIONS_URL={domain}:{config["rasa_actions_port"]}',
        'RASA_ACTION_ENDPOINT_URL=': f'RASA_ACTION_ENDPOINT_URL={domain}:{config["rasa_actions_port"]}/webhook'
    }
    
    for old_pattern, new_value in replacements.items():
        # Find and replace the line
        lines = content.split('\n')
        for i, line in enumerate(lines):
            if line.startswith(old_pattern):
                lines[i] = new_value
        content = '\n'.join(lines)
    
    # Write updated content
    with open(env_file, 'w') as f:
        f.write(content)
    
    print(f"✓ Updated {env_file}")

def update_domain_config_json(config, project_root):
    """Update the domain-config.json file"""
    config_file = project_root / "aws-deployment" / "config" / "domain-config.json"
    
    if not config_file.exists():
        print(f"Warning: {config_file} not found, skipping domain config update")
        return
    
    # Load existing config
    with open(config_file, 'r') as f:
        domain_config = json.load(f)
    
    # Update based on configuration type
    config_name = get_config_name(config)
    domain = config['domain']
    
    if config_name == "localhost":
        # Update all environments to use localhost
        for env in domain_config['domains']:
            domain_config['domains'][env]['main_domain'] = f"{domain}:{config['frontend_port']}"
            domain_config['domains'][env]['api_domain'] = f"{domain}:{config['backend_port']}"
            domain_config['domains'][env]['widget_domain'] = f"{domain}:{config['backend_port']}"
            domain_config['domains'][env]['admin_domain'] = f"{domain}:{config['backend_port']}"
            domain_config['domains'][env]['ssl_enabled'] = False
            domain_config['domains'][env]['force_https'] = False
    
    elif config_name == "ec2":
        # Update production environment to use EC2 IP
        domain_config['domains']['production']['main_domain'] = f"{domain}:{config['frontend_port']}"
        domain_config['domains']['production']['api_domain'] = f"{domain}:{config['backend_port']}"
        domain_config['domains']['production']['widget_domain'] = f"{domain}:{config['backend_port']}"
        domain_config['domains']['production']['admin_domain'] = f"{domain}:{config['backend_port']}"
        domain_config['domains']['production']['ssl_enabled'] = config['ssl_enabled']
        domain_config['domains']['production']['force_https'] = config['ssl_enabled']
    
    # Update external services
    domain_config['external_services']['rasa_url'] = f"{domain}:{config['rasa_port']}"
    domain_config['external_services']['actions_url'] = f"{domain}:{config['rasa_actions_port']}"
    
    # Write updated config
    with open(config_file, 'w') as f:
        json.dump(domain_config, f, indent=2)
    
    print(f"✓ Updated {config_file}")

def get_config_name(config):
    """Get configuration name based on domain"""
    domain = config['domain']
    if 'localhost' in domain:
        return "localhost"
    elif '54.254.180.103' in domain:
        return "ec2"
    else:
        return "production"

def main():
    parser = argparse.ArgumentParser(
        description="Configure deployment settings for different environments",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  python configure-deployment.py --target localhost    # Configure for local development
  python configure-deployment.py --target ec2         # Configure for EC2 deployment
  python configure-deployment.py --target production  # Configure for production domain
  python configure-deployment.py --custom-domain http://192.168.1.100  # Custom domain
        """
    )
    
    parser.add_argument(
        '--target', 
        choices=['localhost', 'ec2', 'production'],
        help='Deployment target (localhost, ec2, or production)'
    )
    
    parser.add_argument(
        '--custom-domain',
        help='Custom domain/IP address (e.g., http://192.168.1.100)'
    )
    
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Show what would be changed without making changes'
    )
    
    args = parser.parse_args()
    
    if not args.target and not args.custom_domain:
        parser.error("Either --target or --custom-domain must be specified")
    
    # Get configuration
    if args.custom_domain:
        # Create custom configuration
        config = CONFIG_TEMPLATES['localhost'].copy()
        config['domain'] = args.custom_domain.rstrip('/')
    else:
        config = CONFIG_TEMPLATES[args.target].copy()
    
    project_root = get_project_root()
    
    print(f"Configuring deployment for: {get_config_name(config)}")
    print(f"Domain: {config['domain']}")
    print(f"Project root: {project_root}")
    
    if args.dry_run:
        print("\n[DRY RUN] Would update the following files:")
        print(f"  - {project_root}/backend/.env")
        print(f"  - {project_root}/backend/endpoints.yml")
        print(f"  - {project_root}/aws-deployment/environments/.env.production")
        print(f"  - {project_root}/aws-deployment/config/domain-config.json")
        return
    
    print("\nUpdating configuration files...")
    
    try:
        update_backend_env(config, project_root)
        update_rasa_endpoints(config, project_root)
        update_docker_compose_env(config, project_root)
        update_domain_config_json(config, project_root)
        
        print(f"\n✅ Successfully configured deployment for {get_config_name(config)}!")
        print(f"\nConfiguration Summary:")
        print(f"  Domain: {config['domain']}")
        print(f"  Frontend: {config['domain']}:{config['frontend_port']}")
        print(f"  Backend: {config['domain']}:{config['backend_port']}")
        print(f"  RASA: {config['domain']}:{config['rasa_port']}")
        print(f"  RASA Actions: {config['domain']}:{config['rasa_actions_port']}")
        print(f"  SSL Enabled: {config['ssl_enabled']}")
        
        print(f"\nNext steps:")
        if get_config_name(config) == "localhost":
            print(f"  1. Run 'npm run dev:all' to start all services")
            print(f"  2. Access the application at {config['domain']}:{config['frontend_port']}")
        elif get_config_name(config) == "ec2":
            print(f"  1. Build and deploy Docker containers to EC2")
            print(f"  2. Ensure EC2 security groups allow traffic on required ports")
            print(f"  3. Access the application at {config['domain']}:{config['frontend_port']}")
        else:
            print(f"  1. Configure DNS to point to your server")
            print(f"  2. Set up SSL certificates if needed")
            print(f"  3. Deploy the application")
        
    except Exception as e:
        print(f"\n❌ Error updating configuration: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()