import os
import yaml
from typing import Dict, Any

class EnvironmentManager:
    """
    Manages environment-specific configurations for localhost and AWS deployment.
    Handles dynamic switching between environments without affecting existing configurations.
    """
    
    def __init__(self):
        self.env = os.getenv('DEPLOYMENT_ENV', 'localhost')
        self.base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        
    def get_domain(self) -> str:
        """
        Returns the appropriate domain based on deployment environment.
        """
        if self.env == 'aws':
            return os.getenv('AWS_DOMAIN', 'https://your-aws-domain.com')
        else:
            return os.getenv('DOMAIN', 'http://localhost')
    
    def get_rasa_action_endpoint(self) -> str:
        """
        Returns the appropriate Rasa action endpoint URL based on environment.
        """
        domain = self.get_domain()
        port = os.getenv('RASA_ACTIONS_PORT', '5055')
        
        if self.env == 'aws':
            # For AWS, use the full domain without port (assuming load balancer handles routing)
            return f"{domain}/webhook"
        else:
            # For localhost, use domain with port
            return f"{domain}:{port}/webhook"
    
    def get_backend_url(self) -> str:
        """
        Returns the appropriate backend URL based on environment.
        """
        domain = self.get_domain()
        
        if self.env == 'aws':
            return f"{domain}/api"
        else:
            backend_port = os.getenv('BACKEND_PORT', '8000')
            return f"{domain}:{backend_port}/api"
    
    def generate_endpoints_yml(self) -> Dict[str, Any]:
        """
        Generates endpoints.yml configuration based on current environment.
        """
        action_endpoint = self.get_rasa_action_endpoint()
        
        config = {
            'action_endpoint': {
                'url': action_endpoint
            }
        }
        
        # Add environment-specific configurations
        if self.env == 'aws':
            # AWS-specific configurations (if needed)
            config['action_endpoint']['timeout'] = 60
        else:
            # Localhost-specific configurations
            config['action_endpoint']['timeout'] = 30
        
        return config
    
    def write_endpoints_yml(self) -> str:
        """
        Writes the endpoints.yml file based on current environment.
        Returns the path to the generated file.
        """
        config = self.generate_endpoints_yml()
        endpoints_path = os.path.join(self.base_dir, 'endpoints.yml')
        
        # Create a formatted YAML content with comments
        yaml_content = f"""# Auto-generated endpoints.yml for {self.env} environment
# Generated by EnvironmentManager

action_endpoint:
  url: "{config['action_endpoint']['url']}"
  timeout: {config['action_endpoint']['timeout']}

# Uncomment and configure these sections as needed:
# model:
#   url: "http://my-model-server.com/models/default/versions/my-version"
#   token: "my_model_server_token"
#   wait_time_between_pulls: 10

# tracker_store:
#   type: redis
#   url: "localhost"
#   port: 6379
#   db: 0
#   password: "password"
#   record_exp: 30000

# event_broker:
#   type: pika
#   url: "localhost"
#   username: "username"
#   password: "password"
#   queue: "queue"
"""
        
        with open(endpoints_path, 'w', encoding='utf-8') as f:
            f.write(yaml_content)
        
        print(f"Generated endpoints.yml for {self.env} environment at {endpoints_path}")
        return endpoints_path
    
    def get_widget_config(self) -> Dict[str, str]:
        """
        Returns configuration for the test widget based on environment.
        """
        backend_url = self.get_backend_url()
        domain = self.get_domain()
        
        return {
            'DOMAIN': domain,
            'BACKEND_URL': backend_url,
            'CLEVERCOMPANION_BACKEND_URL': backend_url
        }
    
    def is_aws_environment(self) -> bool:
        """
        Returns True if running in AWS environment.
        """
        return self.env == 'aws'
    
    def is_localhost_environment(self) -> bool:
        """